cc_library(
    name = "Calculator",
    srcs = [
        "src/Calculator.cc",
        "src/Adder.h",
        "src/Adder.cc"
    ],
    hdrs = [
        "include/calc/Calculator.h"
    ],
    includes = [
        "include",
        "src"
    ],
    visibility = ["//main:__pkg__"]
)
