# See : https://docs.bazel.build/versions/master/external.html
# See : https://docs.bazel.build/versions/master/repo/git.html

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "gtest",
    remote = "https://github.com/google/googletest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e"
)
